/*
 * This source file was generated by the Gradle 'init' task
 */
package org.pkg.app;

public class App {
    public static void main(String[] args) {
        System.load("/Users/sithi/sandbox/jBridge-backup/shared/native-lib.dylib");

        long isolateThread = createIsolate();

        int result = add(isolateThread, 3, 5);
        System.out.printf("3 + 5 = %d%n", result);
    }

    private static native long createIsolate();

    private static native int add(long isolateThread, int a, int b);

    public static void hello() {
        System.out.println("Hello from Java!");
    }
}
